# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysqlform
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: connection_database
    ports:
      - "6033:3306"
  web:
    container_name: php_web
    build:
        context: ./php
        dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8008:80"